- name: Start beacon node
  hosts: beacon
  gather_facts: true
  serial: 20
  tasks:
    - name: Start Eth2 beacon node container
      docker_container:
        name: "{{ beacon_container_name }}"
        state: started
        image: "{{ beacon_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: host
        restart: "{{ beacon_require_restart | default(false) }}"
        volumes: "{{beacon_volumes}}"
        command: "{{ beacon_start_args }}"
        env: "{{ beacon_env | default({}) }}"
        user: "{{ beacon_user_id }}"
