eth1_client_name: geth
#eth1_image_name: infosecual/instrumented-geth
eth1_image_name: ethereum/client-go:stable
execution_endpoint: http://127.0.0.1:{{eth1_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{eth1_engine_snoop_port}} http://127.0.0.1:{{eth1_engine_port}}"

home_dir: "/home/{{ansible_user}}"

eth1_github_external_user_pubkeys:
  - mariusVanDerWijden

# bare websocket
eth1endpoint_ws: ws://127.0.0.1:8546

eth1_volumes:
  - "{{eth1_node_dir}}:/eth1data"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

geth_init_args: >
  --ropsten --datadir=/eth1data init /networkdata/genesis.json

eth1_start_args: >
  --ropsten
  --datadir=/eth1data
  --networkid={{chainID}}
  --http --http.api "admin,engine,net,eth"
  --http.port {{eth1_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws --ws.api "net,eth,engine"
  --ws.port={{eth1_ws_rpc_port}}
  --ws.addr 0.0.0.0
  --authrpc.port={{eth1_engine_port}}
  --authrpc.addr=0.0.0.0
  --authrpc.vhosts="*"
  --authrpc.jwtsecret=/jwtsecret/jwtsecret.hex
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port={{eth1_metrics_port}}
  --vmodule=rpc=5
  --maxpeers=75
  --override.terminaltotaldifficulty={{terminal_total_difficulty}}

eth1_user_id: "1000:1000"
