##############################################
# image name and image location
##############################################
eth2_client_name: nimbus-ubsan

beacon_image_name: parithoshj/nimbus:merge-79452b7
validator_image_name: parithoshj/nimbus:merge-79452b7
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

eth2_github_external_user_pubkeys:
  - zah
  - tersec
  - etan-status

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "/home/devops/nimbus/beacon:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "/home/devops/nimbus/validator:/validatordata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

beacon_log_level: debug
##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  beacon_node
  --non-interactive=true
  --network="/custom_config_data"
  --max-peers="{{hi_peer_count}}"
  --data-dir="/beacondata"
  --web3-url="{{execution_endpoint}}"
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --bootstrap-node="{{ bootnode_enrs | join(',') }}"
  {% endif %}
  --udp-port={{nimbus_beacon_p2p_port}}
  --tcp-port={{nimbus_beacon_p2p_port}}
  --listen-address=0.0.0.0
  --graffiti="{{graffiti}}"
  --nat="extip:{{ansible_host}}"
  --enr-auto-update=false
  --rest --rest-port={{beacon_api_port}} --rest-address=0.0.0.0
  --metrics --metrics-port={{beacon_metrics_port}} --metrics-address=0.0.0.0
  --log-level="{{ beacon_log_level | upper }}"
  --doppelganger-detection=off
  {% if no_validator_keys != 'true' %}
  --validators-dir="/validatordata/keys"
  --secrets-dir="/validatordata/secrets"
  {% endif %}
  --terminal-total-difficulty-override={{terminal_total_difficulty}}
  --jwt-secret=/jwtsecret/jwtsecret.hex
  --dump:on

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:100"
validator_user_id: "1000:100"

# Nimbus currently runs on a combined beacon validator process, future versions will work as separate processes
separate_validator_process_enabled: false
