version: "3.4"
services:
  prysm_beacon:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:kintsugi-30ed0d
    container_name: prysm_beacon
    volumes:
      - ./beacon_data:/consensus_data
      - ../../../$TESTNET_NAME/custom_config_data:/custom_config_data
    command: >
      --accept-terms-of-use
      --genesis-state /custom_config_data/genesis.ssz
      --datadir /consensus_data
      --http-web3provider=http://localhost:8545
      --min-sync-peers=1
      --chain-config-file /custom_config_data/config.yaml
      --bootstrap-node $ENR
    network_mode: host
